import type { Source } from "./types";

export const SEED_SOURCES: Source[] = [
  // AI + Health
  {
    id: "seed-01-yt-huberman",
    name: "Huberman Lab",
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UC2D2CMWXMOVWx7giW1n3LIg",
    pillar: "ai-health",
    type: "youtube",
    enabled: true,
  },
  {
    id: "seed-02-yt-lex",
    name: "Lex Fridman",
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCSHZKJJfhK1KBs552byvhHw",
    pillar: "ai-health",
    type: "youtube",
    enabled: true,
  },
  {
    id: "seed-03-reddit-ai",
    name: "r/artificial",
    url: "https://www.reddit.com/r/artificial/.rss",
    pillar: "ai-health",
    type: "reddit",
    enabled: true,
  },
  {
    id: "seed-04-reddit-longevity",
    name: "r/longevity",
    url: "https://www.reddit.com/r/longevity/.rss",
    pillar: "ai-health",
    type: "reddit",
    enabled: true,
  },
  {
    id: "seed-05-article-aiweekly",
    name: "The Batch (DeepLearning.AI)",
    url: "https://www.deeplearning.ai/the-batch/feed/",
    pillar: "ai-health",
    type: "article",
    enabled: true,
  },
  // Tech News
  {
    id: "seed-06-article-hackernews",
    name: "Hacker News (Best)",
    url: "https://hnrss.org/best",
    pillar: "tech-news",
    type: "article",
    enabled: true,
  },
  {
    id: "seed-07-article-techcrunch",
    name: "TechCrunch",
    url: "https://techcrunch.com/feed/",
    pillar: "tech-news",
    type: "article",
    enabled: true,
  },
  {
    id: "seed-08-article-theverge",
    name: "The Verge",
    url: "https://www.theverge.com/rss/index.xml",
    pillar: "tech-news",
    type: "article",
    enabled: true,
  },
  {
    id: "seed-09-reddit-tech",
    name: "r/technology",
    url: "https://www.reddit.com/r/technology/.rss",
    pillar: "tech-news",
    type: "reddit",
    enabled: true,
  },
  {
    id: "seed-10-yt-mkbhd",
    name: "MKBHD",
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCBJycsmduvYEL83R_U4JriQ",
    pillar: "tech-news",
    type: "youtube",
    enabled: true,
  },
  // Finance Tools
  {
    id: "seed-11-reddit-fintech",
    name: "r/fintech",
    url: "https://www.reddit.com/r/fintech/.rss",
    pillar: "finance-tools",
    type: "reddit",
    enabled: true,
  },
  {
    id: "seed-12-reddit-investing",
    name: "r/investing",
    url: "https://www.reddit.com/r/investing/.rss",
    pillar: "finance-tools",
    type: "reddit",
    enabled: true,
  },
  {
    id: "seed-13-yt-pbd",
    name: "Patrick Boyle",
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCASM0cgfkJxQ1ICmRilfHLQ",
    pillar: "finance-tools",
    type: "youtube",
    enabled: true,
  },
  {
    id: "seed-14-article-finshots",
    name: "Finshots",
    url: "https://finshots.in/feed/",
    pillar: "finance-tools",
    type: "article",
    enabled: true,
  },
];
